// Generated by CoffeeScript 1.10.0
(function() {
  var LocalStrategy, Post, User, app, async, bcrypt, bodyParser, cookieParser, express, fs, http, io, passport, people, requireRoutes, session, twoDigits;

  express = require('express');

  bodyParser = require('body-parser');

  cookieParser = require('cookie-parser');

  session = require('express-session');

  passport = require('passport');

  bcrypt = require('bcrypt-nodejs');

  async = require('async');

  fs = require('fs');

  requireRoutes = require('express-require-routes');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(bodyParser.json());

  app.set('views', __dirname + '/views');

  app.set('view engine', 'ejs');

  app.use(express["static"](__dirname + '/public'));

  Post = require("./models/post");

  User = require("./models/user");

  LocalStrategy = require('passport-local').Strategy;

  passport.use(new LocalStrategy(function(username, password, done) {
    return User.forge({
      username: username
    }).fetch().then(function(data) {
      var user;
      user = data;
      if (user === null) {
        return done(null, false, {
          message: 'Неверное имя пользователя или пароль'
        });
      } else {
        user = data.toJSON();
        if (!bcrypt.compareSync(password, user.password)) {
          return done(null, false, {
            message: 'Неверное имя пользователя или пароль'
          });
        } else {
          return done(null, user);
        }
      }
    });
  }));

  passport.serializeUser(function(user, done) {
    return done(null, user.username);
  });

  passport.deserializeUser(function(username, done) {
    return User.forge({
      username: username
    }).fetch().then(function(user) {
      return done(null, user);
    });
  });

  app.use(cookieParser());

  app.use(session({
    secret: 'swordfish1992'
  }));

  app.use(passport.initialize());

  app.use(passport.session());

  app.locals.menu = require('./menu');

  twoDigits = function(d) {
    if (0 <= d && d < 10) {
      return "0" + d.toString();
    }
    if (-10 < d && d < 0) {
      return "-0" + (-1 * d).toString();
    }
    return d.toString();
  };

  Date.prototype.toMysqlFormat = function() {
    return this.getUTCFullYear() + "-" + twoDigits(1 + this.getUTCMonth()) + "-" + twoDigits(this.getUTCDate()) + " " + twoDigits(this.getUTCHours()) + ":" + twoDigits(this.getUTCMinutes()) + ":" + twoDigits(this.getUTCSeconds());
  };

  http.listen(3000, function() {
    return console.log('listening on *:3000');
  });

  people = {};

  io.on('connection', function(socket) {
    console.log('a user connected');
    socket.on('disconnect', function() {
      console.log('user disconnected');
      io.emit("update", people[socket.id] + " ушел нахуй с сервера");
      delete people[socket.id];
      return io.emit("update-people", people);
    });
    socket.on('chat message', function(msg) {
      console.log('message: ' + msg);
      return io.emit('chat message', msg);
    });
    socket.on('join', function(name) {
      console.log(name);
      people[socket.id] = name;
      socket.emit('update', 'Вы присоединились к серверу');
      io.emit('update', name + ' присоединился к серверу');
      return io.emit('update-people', people);
    });
    return socket.on('send', function(msg) {
      console.log(msg);
      console.log(people[socket.id]);
      return io.emit('chat', people[socket.id], msg);
    });
  });

  app.post('/auth', function(req, res) {
    return passport.authenticate('local', {
      successRedirect: '/admin',
      failureRedirect: '/auth'
    }, function(err, user, info) {
      if (err) {
        return res.render('auth', {
          activeMenuItem: '/auth/',
          title: 'Авторизация',
          message: err.message
        });
      }
      if (!user) {
        return res.render('auth', {
          activeMenuItem: '/auth/',
          title: 'Авторизация',
          message: info.message
        });
      }
      return req.logIn(user, function(err) {
        if (err) {
          return res.render('auth', {
            activeMenuItem: '/auth/',
            title: 'Авторизация',
            message: err.message
          });
        } else {
          return res.redirect('/admin');
        }
      });
    })(req, res);
  });

  requireRoutes('controllers', app);

}).call(this);

//# sourceMappingURL=app.js.map
