// Generated by CoffeeScript 1.10.0
(function() {
  var Config;

  Config = {
    client: 'mysql',
    connection: {
      host: 'localhost',
      port: '31006',
      user: 'root',
      password: '',
      database: 'node',
      charset: 'utf8'
    }
  };

  module.exports = Config;

}).call(this);

//# sourceMappingURL=config.js.map
