// Generated by CoffeeScript 1.10.0
(function() {
  var Schema;

  Schema = {
    posts: {
      id: {
        type: 'increments',
        nullable: false,
        primary: true
      },
      title: {
        type: 'string',
        maxlength: 150,
        nullable: false
      },
      html: {
        type: 'text',
        fieldtype: 'text',
        nullable: false
      },
      created_at: {
        type: 'dateTime',
        nullable: false
      },
      updated_at: {
        type: 'dateTime',
        nullable: true
      }
    }
  };

  module.exports = Schema;

}).call(this);

//# sourceMappingURL=schema.js.map
