// Generated by CoffeeScript 1.10.0
(function() {
  var Config, Post, bookshelf, knex;

  Config = require('../config');

  knex = require('knex')(Config);

  bookshelf = require('bookshelf')(knex);

  Post = bookshelf.Model.extend({
    tableName: 'posts'
  });

  module.exports = Post;

}).call(this);

//# sourceMappingURL=post.js.map
